### ISSUE TITLE
Assign this.thunk to null instead of deleting it

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript-lazy#15]
When you use `delete` on a property, V8 will demote the object to a hash table instead of the original compact sequence of words. Setting the property to `null` will keep the compact representation.

- https://groups.google.com/forum/#!topic/v8-users/zE4cOHBkAnY
- https://www.youtube.com/watch?v=YPkPYqoinU8

**Comment by paf31** [comment]
👍
